name: Desplegar aplicacion HTML 5 de Tareas 
on:
	push:
		branches:
			- main
jobs:
	deploy-page:
		runs-on: ubuntu-lastest
		steps:
			- name: Checkout
			  uses: actions/checkout@v2.3.1

			- name: Deploy
			  uses: JamesIves/github-pages-deploy-action@4.1.4
			  with:
				branch: hg-html5 #La rama a crear en el repositorio
				folder: . #El folder donde se despliega la accion